logging:
  level:
    org.springframework.security: DEBUG
spring:
  profiles:
    active: dev
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  servlet:
    context-path: /