package group.slsd.vo;

public class ownerVo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column owner.owner_id
     *
     * @mbg.generated Mon Aug 26 15:10:20 CST 2019
     */
    private Integer ownerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column owner.owner_name
     *
     * @mbg.generated Mon Aug 26 15:10:20 CST 2019
     */
    private String ownerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column owner.uname
     *
     * @mbg.generated Mon Aug 26 15:10:20 CST 2019
     */
    private String uname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column owner.pwd
     *
     * @mbg.generated Mon Aug 26 15:10:20 CST 2019
     */
    private String pwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column owner.hsize
     *
     * @mbg.generated Mon Aug 26 15:10:20 CST 2019
     */
    private Float hsize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column owner.num
     *
     * @mbg.generated Mon Aug 26 15:10:20 CST 2019
     */
    private Integer num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column owner.tel
     *
     * @mbg.generated Mon Aug 26 15:10:20 CST 2019
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column owner.pro
     *
     * @mbg.generated Mon Aug 26 15:10:20 CST 2019
     */
    private String pro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column owner.hourse_id
     *
     * @mbg.generated Mon Aug 26 15:10:20 CST 2019
     */
    private Integer hourseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column owner.address
     *
     * @mbg.generated Mon Aug 26 15:10:20 CST 2019
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column owner.iscar
     *
     * @mbg.generated Mon Aug 26 15:10:20 CST 2019
     */
    private Boolean iscar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column owner.car_id
     *
     * @mbg.generated Mon Aug 26 15:10:20 CST 2019
     */
    private Integer carId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column owner.cartype
     *
     * @mbg.generated Mon Aug 26 15:10:20 CST 2019
     */
    private String cartype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column owner.owner_id
     *
     * @return the value of owner.owner_id
     *
     * @mbg.generated Mon Aug 26 15:10:20 CST 2019
     */
    public Integer getOwnerId() {
        return ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column owner.owner_id
     *
     * @param ownerId the value for owner.owner_id
     *
     * @mbg.generated Mon Aug 26 15:10:20 CST 2019
     */
    public void setOwnerId(Integer ownerId) {
        this.ownerId = ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column owner.owner_name
     *
     * @return the value of owner.owner_name
     *
     * @mbg.generated Mon Aug 26 15:10:20 CST 2019
     */
    public String getOwnerName() {
        return ownerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column owner.owner_name
     *
     * @param ownerName the value for owner.owner_name
     *
     * @mbg.generated Mon Aug 26 15:10:20 CST 2019
     */
    public void setOwnerName(String ownerName) {
        this.ownerName = ownerName == null ? null : ownerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column owner.uname
     *
     * @return the value of owner.uname
     *
     * @mbg.generated Mon Aug 26 15:10:20 CST 2019
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column owner.uname
     *
     * @param uname the value for owner.uname
     *
     * @mbg.generated Mon Aug 26 15:10:20 CST 2019
     */
    public void setUname(String uname) {
        this.uname = uname == null ? null : uname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column owner.pwd
     *
     * @return the value of owner.pwd
     *
     * @mbg.generated Mon Aug 26 15:10:20 CST 2019
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column owner.pwd
     *
     * @param pwd the value for owner.pwd
     *
     * @mbg.generated Mon Aug 26 15:10:20 CST 2019
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column owner.hsize
     *
     * @return the value of owner.hsize
     *
     * @mbg.generated Mon Aug 26 15:10:20 CST 2019
     */
    public Float getHsize() {
        return hsize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column owner.hsize
     *
     * @param hsize the value for owner.hsize
     *
     * @mbg.generated Mon Aug 26 15:10:20 CST 2019
     */
    public void setHsize(Float hsize) {
        this.hsize = hsize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column owner.num
     *
     * @return the value of owner.num
     *
     * @mbg.generated Mon Aug 26 15:10:20 CST 2019
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column owner.num
     *
     * @param num the value for owner.num
     *
     * @mbg.generated Mon Aug 26 15:10:20 CST 2019
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column owner.tel
     *
     * @return the value of owner.tel
     *
     * @mbg.generated Mon Aug 26 15:10:20 CST 2019
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column owner.tel
     *
     * @param tel the value for owner.tel
     *
     * @mbg.generated Mon Aug 26 15:10:20 CST 2019
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column owner.pro
     *
     * @return the value of owner.pro
     *
     * @mbg.generated Mon Aug 26 15:10:20 CST 2019
     */
    public String getPro() {
        return pro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column owner.pro
     *
     * @param pro the value for owner.pro
     *
     * @mbg.generated Mon Aug 26 15:10:20 CST 2019
     */
    public void setPro(String pro) {
        this.pro = pro == null ? null : pro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column owner.hourse_id
     *
     * @return the value of owner.hourse_id
     *
     * @mbg.generated Mon Aug 26 15:10:20 CST 2019
     */
    public Integer getHourseId() {
        return hourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column owner.hourse_id
     *
     * @param hourseId the value for owner.hourse_id
     *
     * @mbg.generated Mon Aug 26 15:10:20 CST 2019
     */
    public void setHourseId(Integer hourseId) {
        this.hourseId = hourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column owner.address
     *
     * @return the value of owner.address
     *
     * @mbg.generated Mon Aug 26 15:10:20 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column owner.address
     *
     * @param address the value for owner.address
     *
     * @mbg.generated Mon Aug 26 15:10:20 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column owner.iscar
     *
     * @return the value of owner.iscar
     *
     * @mbg.generated Mon Aug 26 15:10:20 CST 2019
     */
    public Boolean getIscar() {
        return iscar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column owner.iscar
     *
     * @param iscar the value for owner.iscar
     *
     * @mbg.generated Mon Aug 26 15:10:20 CST 2019
     */
    public void setIscar(Boolean iscar) {
        this.iscar = iscar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column owner.car_id
     *
     * @return the value of owner.car_id
     *
     * @mbg.generated Mon Aug 26 15:10:20 CST 2019
     */
    public Integer getCarId() {
        return carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column owner.car_id
     *
     * @param carId the value for owner.car_id
     *
     * @mbg.generated Mon Aug 26 15:10:20 CST 2019
     */
    public void setCarId(Integer carId) {
        this.carId = carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column owner.cartype
     *
     * @return the value of owner.cartype
     *
     * @mbg.generated Mon Aug 26 15:10:20 CST 2019
     */
    public String getCartype() {
        return cartype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column owner.cartype
     *
     * @param cartype the value for owner.cartype
     *
     * @mbg.generated Mon Aug 26 15:10:20 CST 2019
     */
    public void setCartype(String cartype) {
        this.cartype = cartype == null ? null : cartype.trim();
    }
}