package group.slsd.vo;

public class workerVo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker.emp_id
     *
     * @mbg.generated Mon Aug 26 15:10:20 CST 2019
     */
    private Integer empId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker.emp_name
     *
     * @mbg.generated Mon Aug 26 15:10:20 CST 2019
     */
    private String empName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker.u_name
     *
     * @mbg.generated Mon Aug 26 15:10:20 CST 2019
     */
    private String uName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker.pwd
     *
     * @mbg.generated Mon Aug 26 15:10:20 CST 2019
     */
    private String pwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker.emp_position
     *
     * @mbg.generated Mon Aug 26 15:10:20 CST 2019
     */
    private String empPosition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker.emp_tel
     *
     * @mbg.generated Mon Aug 26 15:10:20 CST 2019
     */
    private String empTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker.emp_descript
     *
     * @mbg.generated Mon Aug 26 15:10:20 CST 2019
     */
    private String empDescript;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker.roles
     *
     * @mbg.generated Mon Aug 26 15:10:20 CST 2019
     */
    private String roles;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker.emp_id
     *
     * @return the value of worker.emp_id
     *
     * @mbg.generated Mon Aug 26 15:10:20 CST 2019
     */
    public Integer getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker.emp_id
     *
     * @param empId the value for worker.emp_id
     *
     * @mbg.generated Mon Aug 26 15:10:20 CST 2019
     */
    public void setEmpId(Integer empId) {
        this.empId = empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker.emp_name
     *
     * @return the value of worker.emp_name
     *
     * @mbg.generated Mon Aug 26 15:10:20 CST 2019
     */
    public String getEmpName() {
        return empName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker.emp_name
     *
     * @param empName the value for worker.emp_name
     *
     * @mbg.generated Mon Aug 26 15:10:20 CST 2019
     */
    public void setEmpName(String empName) {
        this.empName = empName == null ? null : empName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker.u_name
     *
     * @return the value of worker.u_name
     *
     * @mbg.generated Mon Aug 26 15:10:20 CST 2019
     */
    public String getuName() {
        return uName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker.u_name
     *
     * @param uName the value for worker.u_name
     *
     * @mbg.generated Mon Aug 26 15:10:20 CST 2019
     */
    public void setuName(String uName) {
        this.uName = uName == null ? null : uName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker.pwd
     *
     * @return the value of worker.pwd
     *
     * @mbg.generated Mon Aug 26 15:10:20 CST 2019
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker.pwd
     *
     * @param pwd the value for worker.pwd
     *
     * @mbg.generated Mon Aug 26 15:10:20 CST 2019
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker.emp_position
     *
     * @return the value of worker.emp_position
     *
     * @mbg.generated Mon Aug 26 15:10:20 CST 2019
     */
    public String getEmpPosition() {
        return empPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker.emp_position
     *
     * @param empPosition the value for worker.emp_position
     *
     * @mbg.generated Mon Aug 26 15:10:20 CST 2019
     */
    public void setEmpPosition(String empPosition) {
        this.empPosition = empPosition == null ? null : empPosition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker.emp_tel
     *
     * @return the value of worker.emp_tel
     *
     * @mbg.generated Mon Aug 26 15:10:20 CST 2019
     */
    public String getEmpTel() {
        return empTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker.emp_tel
     *
     * @param empTel the value for worker.emp_tel
     *
     * @mbg.generated Mon Aug 26 15:10:20 CST 2019
     */
    public void setEmpTel(String empTel) {
        this.empTel = empTel == null ? null : empTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker.emp_descript
     *
     * @return the value of worker.emp_descript
     *
     * @mbg.generated Mon Aug 26 15:10:20 CST 2019
     */
    public String getEmpDescript() {
        return empDescript;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker.emp_descript
     *
     * @param empDescript the value for worker.emp_descript
     *
     * @mbg.generated Mon Aug 26 15:10:20 CST 2019
     */
    public void setEmpDescript(String empDescript) {
        this.empDescript = empDescript == null ? null : empDescript.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker.roles
     *
     * @return the value of worker.roles
     *
     * @mbg.generated Mon Aug 26 15:10:20 CST 2019
     */
    public String getRoles() {
        return roles;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker.roles
     *
     * @param roles the value for worker.roles
     *
     * @mbg.generated Mon Aug 26 15:10:20 CST 2019
     */
    public void setRoles(String roles) {
        this.roles = roles == null ? null : roles.trim();
    }
}