package group.slsd.mapper;

import group.slsd.vo.ownerVo;

public interface ownerVoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table owner
     *
     * @mbg.generated Mon Aug 26 15:10:20 CST 2019
     */
    int deleteByPrimaryKey(Integer ownerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table owner
     *
     * @mbg.generated Mon Aug 26 15:10:20 CST 2019
     */
    int insert(ownerVo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table owner
     *
     * @mbg.generated Mon Aug 26 15:10:20 CST 2019
     */
    int insertSelective(ownerVo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table owner
     *
     * @mbg.generated Mon Aug 26 15:10:20 CST 2019
     */
    ownerVo selectByPrimaryKey(Integer ownerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table owner
     *
     * @mbg.generated Mon Aug 26 15:10:20 CST 2019
     */
    int updateByPrimaryKeySelective(ownerVo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table owner
     *
     * @mbg.generated Mon Aug 26 15:10:20 CST 2019
     */
    int updateByPrimaryKey(ownerVo record);
}