package group.slsd.mapper;

import group.slsd.vo.workerVo;

public interface workerVoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table worker
     *
     * @mbg.generated Mon Aug 26 15:10:20 CST 2019
     */
    int deleteByPrimaryKey(Integer empId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table worker
     *
     * @mbg.generated Mon Aug 26 15:10:20 CST 2019
     */
    int insert(workerVo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table worker
     *
     * @mbg.generated Mon Aug 26 15:10:20 CST 2019
     */
    int insertSelective(workerVo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table worker
     *
     * @mbg.generated Mon Aug 26 15:10:20 CST 2019
     */
    workerVo selectByPrimaryKey(Integer empId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table worker
     *
     * @mbg.generated Mon Aug 26 15:10:20 CST 2019
     */
    int updateByPrimaryKeySelective(workerVo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table worker
     *
     * @mbg.generated Mon Aug 26 15:10:20 CST 2019
     */
    int updateByPrimaryKey(workerVo record);
}