package group.slsd.mapper;

import group.slsd.vo.WorkerVo;

public interface WorkerVoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table worker
     *
     * @mbg.generated Mon Aug 26 15:10:20 CST 2019
     */
    int deleteByPrimaryKey(Integer empId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table worker
     *
     * @mbg.generated Mon Aug 26 15:10:20 CST 2019
     */
    int insert(WorkerVo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table worker
     *
     * @mbg.generated Mon Aug 26 15:10:20 CST 2019
     */
    int insertSelective(WorkerVo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table worker
     *
     * @mbg.generated Mon Aug 26 15:10:20 CST 2019
     */
    WorkerVo selectByPrimaryKey(Integer empId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table worker
     *
     * @mbg.generated Mon Aug 26 15:10:20 CST 2019
     */
    int updateByPrimaryKeySelective(WorkerVo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table worker
     *
     * @mbg.generated Mon Aug 26 15:10:20 CST 2019
     */
    int updateByPrimaryKey(WorkerVo record);
}